<script setup>
import { ref } from 'vue';
import TimelineEventComponent from './TimelineEventComponent.vue';

let ascending = ref(true);

</script>

<template>
    <div class="container">
        <button @click="ascending = !ascending">{{ ascending ? "ASC" : "DESC" }}</button>
        <div :class="{ 'timeline_container': true, 'descending' : !ascending }">
            <TimelineEventComponent
                :timestamp="new Date('2025-12-25T12:00:00Z')"
                type="PRECEDING ACCUSATION"
                user="USER_PROSECUTION"
                summary="Miss Information suspiciously works overtime for several days in a row"
            />
            <TimelineEventComponent
                :timestamp="new Date('2026-02-10T23:50:24Z')"
                type="PRECEDING ACCUSATION"
                user="USER_PROSECUTION"
                summary="Miss Information tells her husband that she needs to attend a company meeting in Charlotte, NC on Valentine's Day"
            />
            <TimelineEventComponent
                :timestamp="new Date('2026-02-14T20:22:58Z')"
                type="PRECEDING ACCUSATION"
                user="USER_PROSECUTION"
                summary="Miss Information is allegedly spotted with Mr. Dimmesdale at the Carowinds amusement park"
            />
            <TimelineEventComponent
                :timestamp="new Date('2026-02-15T14:13:06Z')"
                type="CASE FILED"
                user="ADMIN"
                summary="Mr. Siren files for divorce from Miss Information, citing her infidelity"
            />
            <TimelineEventComponent
                :timestamp="new Date('2026-02-15T16:30:45Z')"
                type="EVIDENCE SUBMITTED"
                user="DETECTIVE"
                summary="Mr. Siren submits his video footage of the suspects together at Carowinds as evidence for the case"
            />
            <TimelineEventComponent
                :timestamp="new Date('2026-02-16T23:14:49Z')"
                type="LEGAL CLAIM SUBMITTED"
                user="USER_DEFENSE"
                summary="Miss Information's legal USER_DEFENSE team claims that the video footage was generated by AI and is therefore not valid evidence"
            />
            <TimelineEventComponent
                :timestamp="new Date()"
                type="CASE ASSIGNED"
                user="ADMIN"
                summary="The Agency assigned you to work as the Detective on CASE NO.20260214 (&quot;Siren's Call&quot;)"
            />
        </div>
    </div>
</template>

<style scoped>
.timeline_container, .container {
    display: flex;
    flex-direction: column;
    gap: 1em;
}

.container {
    align-items: flex-start;
}

.descending {
    flex-direction: column-reverse;
}
</style>

